
name: Java CI with Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Increase patch version
      id: versioning
      run: |
        VERSION=$(./gradlew properties -q | grep "^version:" | awk '{print $2}')
        IFS='.' read -ra ADDR <<< "$VERSION"
        PATCH=$((ADDR[2]+1))
        NEW_VERSION="${ADDR[0]}.${ADDR[1]}.$PATCH"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "::set-output name=new_version::$NEW_VERSION"
      shell: bash

    - name: Build with Gradle
      run: ./gradlew build -Pversion=${{ env.NEW_VERSION }}

    - name: Package JAR
      run: ./gradlew jar

    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag maxskalt/helloworld:${{ steps.versioning.outputs.new_version }}
        docker tag maxskalt/helloworld:${{ steps.versioning.outputs.new_version }} maxskalt/helloworld:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image to Docker Hub
      run: |
        docker push maxskalt/helloworld:${{ steps.versioning.outputs.new_version }}
        docker push maxskalt/helloworld:latest

    - name: Pull and Run Docker Image
      run: |
        docker pull maxskalt/helloworld:${{ steps.versioning.outputs.new_version }}
        docker run --user 1000:1000 -d maxskalt/helloworld:${{ steps.versioning.outputs.new_version }}
